# Generated by Django 5.2.5 on 2025-08-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline (optional)', null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='Untitled', help_text='Task name', max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, help_text='Task description', max_length=255),
        ),
    ]
