# Generated by Django 5.2.5 on 2025-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_deadline_todo_name_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Time of deletion (for soft delete)', null=True),
        ),
    ]
